/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedTrendingRouteImport } from './routes/_protected/trending'
import { Route as ProtectedSearchRouteImport } from './routes/_protected/search'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPreferencesRouteImport } from './routes/_protected/preferences'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedFridgeRouteImport } from './routes/_protected/fridge'
import { Route as ProtectedFavoritesRouteImport } from './routes/_protected/favorites'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as PublicMainRouteRouteImport } from './routes/_public/_main/route'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PublicMainIndexRouteImport } from './routes/_public/_main/index'
import { Route as PublicMainAboutRouteImport } from './routes/_public/_main/about'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as ProtectedRecipesRecipeIdRouteImport } from './routes/_protected/recipes.$recipeId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTrendingRoute = ProtectedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchRoute = ProtectedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPreferencesRoute = ProtectedPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFridgeRoute = ProtectedFridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicMainRouteRoute = PublicMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicMainIndexRoute = PublicMainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicMainRouteRoute,
} as any)
const PublicMainAboutRoute = PublicMainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicMainRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const ProtectedRecipesRecipeIdRoute =
  ProtectedRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicMainIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/fridge': typeof ProtectedFridgeRoute
  '/home': typeof ProtectedHomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/profile': typeof ProtectedProfileRoute
  '/search': typeof ProtectedSearchRoute
  '/trending': typeof ProtectedTrendingRoute
  '/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/about': typeof PublicMainAboutRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicMainIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/fridge': typeof ProtectedFridgeRoute
  '/home': typeof ProtectedHomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/profile': typeof ProtectedProfileRoute
  '/search': typeof ProtectedSearchRoute
  '/trending': typeof ProtectedTrendingRoute
  '/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/about': typeof PublicMainAboutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_public/_main': typeof PublicMainRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/fridge': typeof ProtectedFridgeRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/preferences': typeof ProtectedPreferencesRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/search': typeof ProtectedSearchRoute
  '/_protected/trending': typeof ProtectedTrendingRoute
  '/_protected/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/_main/about': typeof PublicMainAboutRoute
  '/_public/_main/': typeof PublicMainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/fridge'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/search'
    | '/trending'
    | '/recipes/$recipeId'
    | '/login'
    | '/register'
    | '/about'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/favorites'
    | '/fridge'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/search'
    | '/trending'
    | '/recipes/$recipeId'
    | '/login'
    | '/register'
    | '/about'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/_auth'
    | '/_public/_main'
    | '/_protected/dashboard'
    | '/_protected/favorites'
    | '/_protected/fridge'
    | '/_protected/home'
    | '/_protected/preferences'
    | '/_protected/profile'
    | '/_protected/search'
    | '/_protected/trending'
    | '/_protected/recipes/$recipeId'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/_main/about'
    | '/_public/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/trending': {
      id: '/_protected/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof ProtectedTrendingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/preferences': {
      id: '/_protected/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof ProtectedPreferencesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fridge': {
      id: '/_protected/fridge'
      path: '/fridge'
      fullPath: '/fridge'
      preLoaderRoute: typeof ProtectedFridgeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/_main': {
      id: '/_public/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicMainRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_main/': {
      id: '/_public/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicMainIndexRouteImport
      parentRoute: typeof PublicMainRouteRoute
    }
    '/_public/_main/about': {
      id: '/_public/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicMainAboutRouteImport
      parentRoute: typeof PublicMainRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_protected/recipes/$recipeId': {
      id: '/_protected/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedRecipesRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedFridgeRoute: typeof ProtectedFridgeRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedPreferencesRoute: typeof ProtectedPreferencesRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSearchRoute: typeof ProtectedSearchRoute
  ProtectedTrendingRoute: typeof ProtectedTrendingRoute
  ProtectedRecipesRecipeIdRoute: typeof ProtectedRecipesRecipeIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedFridgeRoute: ProtectedFridgeRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedPreferencesRoute: ProtectedPreferencesRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSearchRoute: ProtectedSearchRoute,
  ProtectedTrendingRoute: ProtectedTrendingRoute,
  ProtectedRecipesRecipeIdRoute: ProtectedRecipesRecipeIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicMainRouteRouteChildren {
  PublicMainAboutRoute: typeof PublicMainAboutRoute
  PublicMainIndexRoute: typeof PublicMainIndexRoute
}

const PublicMainRouteRouteChildren: PublicMainRouteRouteChildren = {
  PublicMainAboutRoute: PublicMainAboutRoute,
  PublicMainIndexRoute: PublicMainIndexRoute,
}

const PublicMainRouteRouteWithChildren = PublicMainRouteRoute._addFileChildren(
  PublicMainRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicMainRouteRoute: typeof PublicMainRouteRouteWithChildren
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicMainRouteRoute: PublicMainRouteRouteWithChildren,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
