/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProtectedTrendingRouteImport } from './routes/_protected/trending'
import { Route as ProtectedSearchRouteImport } from './routes/_protected/search'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPreferencesRouteImport } from './routes/_protected/preferences'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedFridgeRouteImport } from './routes/_protected/fridge'
import { Route as ProtectedFavoritesRouteImport } from './routes/_protected/favorites'
import { Route as PublicAuthRouteRouteImport } from './routes/_public/_auth/route'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as ProtectedRecipesRecipeIdRouteImport } from './routes/_protected/recipes.$recipeId'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedTrendingRoute = ProtectedTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchRoute = ProtectedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPreferencesRoute = ProtectedPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFridgeRoute = ProtectedFridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicAuthRouteRoute = PublicAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRouteRoute,
} as any)
const ProtectedRecipesRecipeIdRoute =
  ProtectedRecipesRecipeIdRouteImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/favorites': typeof ProtectedFavoritesRoute
  '/fridge': typeof ProtectedFridgeRoute
  '/home': typeof ProtectedHomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/profile': typeof ProtectedProfileRoute
  '/search': typeof ProtectedSearchRoute
  '/trending': typeof ProtectedTrendingRoute
  '/': typeof PublicIndexRoute
  '/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/favorites': typeof ProtectedFavoritesRoute
  '/fridge': typeof ProtectedFridgeRoute
  '/home': typeof ProtectedHomeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/profile': typeof ProtectedProfileRoute
  '/search': typeof ProtectedSearchRoute
  '/trending': typeof ProtectedTrendingRoute
  '/': typeof PublicIndexRoute
  '/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteRouteWithChildren
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/fridge': typeof ProtectedFridgeRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/preferences': typeof ProtectedPreferencesRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/search': typeof ProtectedSearchRoute
  '/_protected/trending': typeof ProtectedTrendingRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/recipes/$recipeId': typeof ProtectedRecipesRecipeIdRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/favorites'
    | '/fridge'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/search'
    | '/trending'
    | '/'
    | '/recipes/$recipeId'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/favorites'
    | '/fridge'
    | '/home'
    | '/preferences'
    | '/profile'
    | '/search'
    | '/trending'
    | '/'
    | '/recipes/$recipeId'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/_auth'
    | '/_protected/favorites'
    | '/_protected/fridge'
    | '/_protected/home'
    | '/_protected/preferences'
    | '/_protected/profile'
    | '/_protected/search'
    | '/_protected/trending'
    | '/_public/'
    | '/_protected/recipes/$recipeId'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/trending': {
      id: '/_protected/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof ProtectedTrendingRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/preferences': {
      id: '/_protected/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof ProtectedPreferencesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/fridge': {
      id: '/_protected/fridge'
      path: '/fridge'
      fullPath: '/fridge'
      preLoaderRoute: typeof ProtectedFridgeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicAuthRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRouteRoute
    }
    '/_protected/recipes/$recipeId': {
      id: '/_protected/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedRecipesRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedFridgeRoute: typeof ProtectedFridgeRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedPreferencesRoute: typeof ProtectedPreferencesRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSearchRoute: typeof ProtectedSearchRoute
  ProtectedTrendingRoute: typeof ProtectedTrendingRoute
  ProtectedRecipesRecipeIdRoute: typeof ProtectedRecipesRecipeIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedFridgeRoute: ProtectedFridgeRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedPreferencesRoute: ProtectedPreferencesRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSearchRoute: ProtectedSearchRoute,
  ProtectedTrendingRoute: ProtectedTrendingRoute,
  ProtectedRecipesRecipeIdRoute: ProtectedRecipesRecipeIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicAuthRouteRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
}

const PublicAuthRouteRouteChildren: PublicAuthRouteRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
}

const PublicAuthRouteRouteWithChildren = PublicAuthRouteRoute._addFileChildren(
  PublicAuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRouteRoute: typeof PublicAuthRouteRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRouteRoute: PublicAuthRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
