export const ErrorCodes = {
  AUTH_INVALID: "AUTH_001",
  AUTH_UNAUTHORIZED: "AUTH_002",
  AUTH_EXPIRED: "AUTH_003",

  VAL_FAILED: "VAL_001",
  VAL_INVALID_TYPE: "VAL_002",
  VAL_INVALID_FORMAT: "VAL_003",
  VAL_MISSING_FIELD: "VAL_004",

  RES_NOT_FOUND: "RES_001",
  RES_CONFLICT: "RES_002",
  RES_CONFLICT_EMAIL: "RES_003",
  RES_CONFLICT_USERNAME: "RES_004",

  RL_EXCEEDED: "RL_001",

  SPN_API_ERROR: "EXT_001",
  SPN_API_QUOTA: "EXT_002",
  EMB_SERVICE_ERROR: "EXT_003",

  SYS_INTERNAL_ERROR: "SYS_001",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
